In [1]:
import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.rand(4,4))
df.columns=['Random value 1','Random value 2','Random value 3','Random value 4']
df.describe()
df.isnull()
df.info()
df.loc[:,'Random value 2':'Random value 3']
df.iloc[:,1:3]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random value 1  4 non-null      float64
 1   Random value 2  4 non-null      float64
 2   Random value 3  4 non-null      float64
 3   Random value 4  4 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes

   Random value 2  Random value 3
0        0.944719        0.093347
1        0.297979        0.232078
2        0.041980        0.800974
3        0.471635        0.168648